### ISSUE TITLE
Not compatible with v4.1 version of selenium and v115 version of Chrome

### ISSUE THREAD

**Issue by nitinkumar30** [RoastSea8/chromedriver_autoinstall#1]
This library is not compatible with v4.1 version of selenium and v115 version of Chrome. I'm getting attached error while running the below script.

```
PATH = "./chromedriver"
    URL = "https://github.com/RoastSea8/chromedriver-autoinstaller"

    chromedriver_autoinstall.install()
    # os.chmod('./chromedriver', 0o755) # MacOS only
    driver = webdriver.Chrome(PATH)
    driver.get(URL)
    time.sleep(1000)
```

<img width="925" alt="image" src="https://github.com/RoastSea8/chromedriver_autoinstall/assets/40369168/24120646-d7cb-4dbb-ad81-e0bb575ca654">

**Comment by adistomar** [comment]
@nitinkumar30 The issue is fixed. The README example has been updated. You can update the pip package to get the recent changes.

**Comment by adistomar** [comment]
@nitinkumar30 Wanted to follow up. I've released a new version of the package to fix another issue, so you can update your pip package to get the fixes. Does the package work for you?
